/* This file is automatically generated by aarch64-gen.  Do not edit!  */
/* Copyright 2012, 2013  Free Software Foundation, Inc.
   Contributed by ARM Ltd.

   This file is part of the GNU opcodes library.

   This library is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3, or (at your option)
   any later version.

   It is distributed in the hope that it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
   or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
   License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; see the file COPYING3. If not,
   see <http://www.gnu.org/licenses/>.  */

#include "sysdep.h"
#include "aarch64-asm.h"


const aarch64_opcode *
aarch64_find_real_opcode (const aarch64_opcode *opcode)
{
  /* Use the index as the key to locate the real opcode.  */
  int key = opcode - aarch64_opcode_table;
  int value;
  switch (key)
    {
    case 3:	/* ngc */
      value = 2;	/* --> sbc.  */
      break;
    case 5:	/* ngcs */
      value = 4;	/* --> sbcs.  */
      break;
    case 8:	/* cmn */
      value = 7;	/* --> adds.  */
      break;
    case 11:	/* cmp */
      value = 10;	/* --> subs.  */
      break;
    case 13:	/* mov */
      value = 12;	/* --> add.  */
      break;
    case 15:	/* cmn */
      value = 14;	/* --> adds.  */
      break;
    case 18:	/* cmp */
      value = 17;	/* --> subs.  */
      break;
    case 21:	/* cmn */
      value = 20;	/* --> adds.  */
      break;
    case 23:	/* neg */
      value = 22;	/* --> sub.  */
      break;
    case 26:	/* negs */
    case 25:	/* cmp */
      value = 24;	/* --> subs.  */
      break;
    case 141:	/* mov */
      value = 140;	/* --> umov.  */
      break;
    case 143:	/* mov */
      value = 142;	/* --> ins.  */
      break;
    case 145:	/* mov */
      value = 144;	/* --> ins.  */
      break;
    case 206:	/* mvn */
      value = 205;	/* --> not.  */
      break;
    case 261:	/* mov */
      value = 260;	/* --> orr.  */
      break;
    case 318:	/* sxtl */
      value = 317;	/* --> sshll.  */
      break;
    case 320:	/* sxtl2 */
      value = 319;	/* --> sshll2.  */
      break;
    case 340:	/* uxtl */
      value = 339;	/* --> ushll.  */
      break;
    case 342:	/* uxtl2 */
      value = 341;	/* --> ushll2.  */
      break;
    case 437:	/* mov */
      value = 436;	/* --> dup.  */
      break;
    case 506:	/* sxtw */
    case 505:	/* sxth */
    case 504:	/* sxtb */
    case 507:	/* asr */
    case 503:	/* sbfx */
    case 502:	/* sbfiz */
      value = 501;	/* --> sbfm.  */
      break;
    case 510:	/* bfxil */
    case 509:	/* bfi */
      value = 508;	/* --> bfm.  */
      break;
    case 515:	/* uxth */
    case 514:	/* uxtb */
    case 517:	/* lsr */
    case 516:	/* lsl */
    case 513:	/* ubfx */
    case 512:	/* ubfiz */
      value = 511;	/* --> ubfm.  */
      break;
    case 535:	/* cset */
    case 534:	/* cinc */
      value = 533;	/* --> csinc.  */
      break;
    case 538:	/* csetm */
    case 537:	/* cinv */
      value = 536;	/* --> csinv.  */
      break;
    case 540:	/* cneg */
      value = 539;	/* --> csneg.  */
      break;
    case 565:	/* lsl */
      value = 564;	/* --> lslv.  */
      break;
    case 567:	/* lsr */
      value = 566;	/* --> lsrv.  */
      break;
    case 569:	/* asr */
      value = 568;	/* --> asrv.  */
      break;
    case 571:	/* ror */
      value = 570;	/* --> rorv.  */
      break;
    case 581:	/* mul */
      value = 580;	/* --> madd.  */
      break;
    case 583:	/* mneg */
      value = 582;	/* --> msub.  */
      break;
    case 585:	/* smull */
      value = 584;	/* --> smaddl.  */
      break;
    case 587:	/* smnegl */
      value = 586;	/* --> smsubl.  */
      break;
    case 590:	/* umull */
      value = 589;	/* --> umaddl.  */
      break;
    case 592:	/* umnegl */
      value = 591;	/* --> umsubl.  */
      break;
    case 603:	/* ror */
      value = 602;	/* --> extr.  */
      break;
    case 703:	/* strb */
      value = 701;	/* --> sturb.  */
      break;
    case 704:	/* ldrb */
      value = 702;	/* --> ldurb.  */
      break;
    case 706:	/* ldrsb */
      value = 705;	/* --> ldursb.  */
      break;
    case 709:	/* str */
      value = 707;	/* --> stur.  */
      break;
    case 710:	/* ldr */
      value = 708;	/* --> ldur.  */
      break;
    case 713:	/* strh */
      value = 711;	/* --> sturh.  */
      break;
    case 714:	/* ldrh */
      value = 712;	/* --> ldurh.  */
      break;
    case 716:	/* ldrsh */
      value = 715;	/* --> ldursh.  */
      break;
    case 719:	/* str */
      value = 717;	/* --> stur.  */
      break;
    case 720:	/* ldr */
      value = 718;	/* --> ldur.  */
      break;
    case 722:	/* ldrsw */
      value = 721;	/* --> ldursw.  */
      break;
    case 724:	/* prfm */
      value = 723;	/* --> prfum.  */
      break;
    case 766:	/* bic */
      value = 765;	/* --> and.  */
      break;
    case 768:	/* mov */
      value = 767;	/* --> orr.  */
      break;
    case 771:	/* tst */
      value = 770;	/* --> ands.  */
      break;
    case 776:	/* uxtw */
    case 775:	/* mov */
      value = 774;	/* --> orr.  */
      break;
    case 778:	/* mvn */
      value = 777;	/* --> orn.  */
      break;
    case 782:	/* tst */
      value = 781;	/* --> ands.  */
      break;
    case 908:	/* staddb */
      value = 812;	/* --> ldaddb.  */
      break;
    case 909:	/* staddh */
      value = 813;	/* --> ldaddh.  */
      break;
    case 910:	/* stadd */
      value = 814;	/* --> ldadd.  */
      break;
    case 911:	/* staddlb */
      value = 816;	/* --> ldaddlb.  */
      break;
    case 912:	/* staddlh */
      value = 819;	/* --> ldaddlh.  */
      break;
    case 913:	/* staddl */
      value = 822;	/* --> ldaddl.  */
      break;
    case 914:	/* stclrb */
      value = 824;	/* --> ldclrb.  */
      break;
    case 915:	/* stclrh */
      value = 825;	/* --> ldclrh.  */
      break;
    case 916:	/* stclr */
      value = 826;	/* --> ldclr.  */
      break;
    case 917:	/* stclrlb */
      value = 828;	/* --> ldclrlb.  */
      break;
    case 918:	/* stclrlh */
      value = 831;	/* --> ldclrlh.  */
      break;
    case 919:	/* stclrl */
      value = 834;	/* --> ldclrl.  */
      break;
    case 920:	/* steorb */
      value = 836;	/* --> ldeorb.  */
      break;
    case 921:	/* steorh */
      value = 837;	/* --> ldeorh.  */
      break;
    case 922:	/* steor */
      value = 838;	/* --> ldeor.  */
      break;
    case 923:	/* steorlb */
      value = 840;	/* --> ldeorlb.  */
      break;
    case 924:	/* steorlh */
      value = 843;	/* --> ldeorlh.  */
      break;
    case 925:	/* steorl */
      value = 846;	/* --> ldeorl.  */
      break;
    case 926:	/* stsetb */
      value = 848;	/* --> ldsetb.  */
      break;
    case 927:	/* stseth */
      value = 849;	/* --> ldseth.  */
      break;
    case 928:	/* stset */
      value = 850;	/* --> ldset.  */
      break;
    case 929:	/* stsetlb */
      value = 852;	/* --> ldsetlb.  */
      break;
    case 930:	/* stsetlh */
      value = 855;	/* --> ldsetlh.  */
      break;
    case 931:	/* stsetl */
      value = 858;	/* --> ldsetl.  */
      break;
    case 932:	/* stsmaxb */
      value = 860;	/* --> ldsmaxb.  */
      break;
    case 933:	/* stsmaxh */
      value = 861;	/* --> ldsmaxh.  */
      break;
    case 934:	/* stsmax */
      value = 862;	/* --> ldsmax.  */
      break;
    case 935:	/* stsmaxlb */
      value = 864;	/* --> ldsmaxlb.  */
      break;
    case 936:	/* stsmaxlh */
      value = 867;	/* --> ldsmaxlh.  */
      break;
    case 937:	/* stsmaxl */
      value = 870;	/* --> ldsmaxl.  */
      break;
    case 938:	/* stsminb */
      value = 872;	/* --> ldsminb.  */
      break;
    case 939:	/* stsminh */
      value = 873;	/* --> ldsminh.  */
      break;
    case 940:	/* stsmin */
      value = 874;	/* --> ldsmin.  */
      break;
    case 941:	/* stsminlb */
      value = 876;	/* --> ldsminlb.  */
      break;
    case 942:	/* stsminlh */
      value = 879;	/* --> ldsminlh.  */
      break;
    case 943:	/* stsminl */
      value = 882;	/* --> ldsminl.  */
      break;
    case 944:	/* stumaxb */
      value = 884;	/* --> ldumaxb.  */
      break;
    case 945:	/* stumaxh */
      value = 885;	/* --> ldumaxh.  */
      break;
    case 946:	/* stumax */
      value = 886;	/* --> ldumax.  */
      break;
    case 947:	/* stumaxlb */
      value = 888;	/* --> ldumaxlb.  */
      break;
    case 948:	/* stumaxlh */
      value = 891;	/* --> ldumaxlh.  */
      break;
    case 949:	/* stumaxl */
      value = 894;	/* --> ldumaxl.  */
      break;
    case 950:	/* stuminb */
      value = 896;	/* --> lduminb.  */
      break;
    case 951:	/* stuminh */
      value = 897;	/* --> lduminh.  */
      break;
    case 952:	/* stumin */
      value = 898;	/* --> ldumin.  */
      break;
    case 953:	/* stuminlb */
      value = 900;	/* --> lduminlb.  */
      break;
    case 954:	/* stuminlh */
      value = 903;	/* --> lduminlh.  */
      break;
    case 955:	/* stuminl */
      value = 906;	/* --> lduminl.  */
      break;
    case 957:	/* mov */
      value = 956;	/* --> movn.  */
      break;
    case 959:	/* mov */
      value = 958;	/* --> movz.  */
      break;
    case 970:	/* sevl */
    case 969:	/* sev */
    case 968:	/* wfi */
    case 967:	/* wfe */
    case 966:	/* yield */
    case 965:	/* nop */
      value = 964;	/* --> hint.  */
      break;
    case 1002:	/* sys */
    case 1001:	/* sys */
    case 979:	/* tlbi */
    case 978:	/* ic */
    case 977:	/* dc */
    case 976:	/* at */
      value = 975;	/* --> sys.  */
      break;
    default: return NULL;
    }

  return aarch64_opcode_table + value;
}

const char*
aarch64_insert_operand (const aarch64_operand *self,
			   const aarch64_opnd_info *info,
			   aarch64_insn *code, const aarch64_inst *inst)
{
  /* Use the index as the key.  */
  int key = self - aarch64_operands;
  switch (key)
    {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 15:
    case 16:
    case 17:
    case 18:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 36:
    case 37:
      return aarch64_ins_regno (self, info, code, inst);
    case 13:
      return aarch64_ins_reg_extended (self, info, code, inst);
    case 14:
      return aarch64_ins_reg_shifted (self, info, code, inst);
    case 19:
      return aarch64_ins_ft (self, info, code, inst);
    case 29:
    case 30:
    case 31:
      return aarch64_ins_reglane (self, info, code, inst);
    case 32:
      return aarch64_ins_reglist (self, info, code, inst);
    case 33:
      return aarch64_ins_ldst_reglist (self, info, code, inst);
    case 34:
      return aarch64_ins_ldst_reglist_r (self, info, code, inst);
    case 35:
      return aarch64_ins_ldst_elemlist (self, info, code, inst);
    case 38:
    case 47:
    case 48:
    case 49:
    case 50:
    case 51:
    case 52:
    case 53:
    case 54:
    case 55:
    case 56:
    case 57:
    case 58:
    case 59:
    case 68:
    case 69:
    case 70:
    case 71:
      return aarch64_ins_imm (self, info, code, inst);
    case 39:
    case 40:
      return aarch64_ins_advsimd_imm_shift (self, info, code, inst);
    case 41:
    case 42:
    case 43:
      return aarch64_ins_advsimd_imm_modified (self, info, code, inst);
    case 60:
      return aarch64_ins_limm (self, info, code, inst);
    case 61:
      return aarch64_ins_aimm (self, info, code, inst);
    case 62:
      return aarch64_ins_imm_half (self, info, code, inst);
    case 63:
      return aarch64_ins_fbits (self, info, code, inst);
    case 65:
    case 66:
      return aarch64_ins_cond (self, info, code, inst);
    case 72:
    case 78:
      return aarch64_ins_addr_simple (self, info, code, inst);
    case 73:
      return aarch64_ins_addr_regoff (self, info, code, inst);
    case 74:
    case 75:
    case 76:
      return aarch64_ins_addr_simm (self, info, code, inst);
    case 77:
      return aarch64_ins_addr_uimm12 (self, info, code, inst);
    case 79:
      return aarch64_ins_simd_addr_post (self, info, code, inst);
    case 80:
      return aarch64_ins_sysreg (self, info, code, inst);
    case 81:
      return aarch64_ins_pstatefield (self, info, code, inst);
    case 82:
    case 83:
    case 84:
    case 85:
      return aarch64_ins_sysins_op (self, info, code, inst);
    case 86:
      return aarch64_ins_cachereg (self, info, code, inst);
    case 87:
      return aarch64_ins_cachezero (self, info, code, inst);
    case 88:
    case 89:
      return aarch64_ins_barrier (self, info, code, inst);
    case 90:
      return aarch64_ins_prfop (self, info, code, inst);
    default: assert (0); abort ();
    }
}
