/* This file is automatically generated by aarch64-gen.  Do not edit!  */
/* Copyright 2012, 2013  Free Software Foundation, Inc.
   Contributed by ARM Ltd.

   This file is part of the GNU opcodes library.

   This library is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3, or (at your option)
   any later version.

   It is distributed in the hope that it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
   or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
   License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; see the file COPYING3. If not,
   see <http://www.gnu.org/licenses/>.  */

#include "sysdep.h"
#include "aarch64-asm.h"


const aarch64_opcode *
aarch64_find_real_opcode (const aarch64_opcode *opcode)
{
  /* Use the index as the key to locate the real opcode.  */
  int key = opcode - aarch64_opcode_table;
  int value;
  switch (key)
    {
    case 3:	/* ngc */
      value = 2;	/* --> sbc.  */
      break;
    case 5:	/* ngcs */
      value = 4;	/* --> sbcs.  */
      break;
    case 8:	/* cmn */
      value = 7;	/* --> adds.  */
      break;
    case 11:	/* cmp */
      value = 10;	/* --> subs.  */
      break;
    case 13:	/* mov */
      value = 12;	/* --> add.  */
      break;
    case 15:	/* cmn */
      value = 14;	/* --> adds.  */
      break;
    case 18:	/* cmp */
      value = 17;	/* --> subs.  */
      break;
    case 21:	/* cmn */
      value = 20;	/* --> adds.  */
      break;
    case 23:	/* neg */
      value = 22;	/* --> sub.  */
      break;
    case 26:	/* negs */
    case 25:	/* cmp */
      value = 24;	/* --> subs.  */
      break;
    case 141:	/* mov */
      value = 140;	/* --> umov.  */
      break;
    case 143:	/* mov */
      value = 142;	/* --> ins.  */
      break;
    case 145:	/* mov */
      value = 144;	/* --> ins.  */
      break;
    case 206:	/* mvn */
      value = 205;	/* --> not.  */
      break;
    case 261:	/* mov */
      value = 260;	/* --> orr.  */
      break;
    case 318:	/* sxtl */
      value = 317;	/* --> sshll.  */
      break;
    case 320:	/* sxtl2 */
      value = 319;	/* --> sshll2.  */
      break;
    case 340:	/* uxtl */
      value = 339;	/* --> ushll.  */
      break;
    case 342:	/* uxtl2 */
      value = 341;	/* --> ushll2.  */
      break;
    case 437:	/* mov */
      value = 436;	/* --> dup.  */
      break;
    case 506:	/* sxtw */
    case 505:	/* sxth */
    case 504:	/* sxtb */
    case 507:	/* asr */
    case 503:	/* sbfx */
    case 502:	/* sbfiz */
      value = 501;	/* --> sbfm.  */
      break;
    case 510:	/* bfxil */
    case 509:	/* bfi */
      value = 508;	/* --> bfm.  */
      break;
    case 515:	/* uxth */
    case 514:	/* uxtb */
    case 517:	/* lsr */
    case 516:	/* lsl */
    case 513:	/* ubfx */
    case 512:	/* ubfiz */
      value = 511;	/* --> ubfm.  */
      break;
    case 535:	/* cset */
    case 534:	/* cinc */
      value = 533;	/* --> csinc.  */
      break;
    case 538:	/* csetm */
    case 537:	/* cinv */
      value = 536;	/* --> csinv.  */
      break;
    case 540:	/* cneg */
      value = 539;	/* --> csneg.  */
      break;
    case 565:	/* lsl */
      value = 564;	/* --> lslv.  */
      break;
    case 567:	/* lsr */
      value = 566;	/* --> lsrv.  */
      break;
    case 569:	/* asr */
      value = 568;	/* --> asrv.  */
      break;
    case 571:	/* ror */
      value = 570;	/* --> rorv.  */
      break;
    case 581:	/* mul */
      value = 580;	/* --> madd.  */
      break;
    case 583:	/* mneg */
      value = 582;	/* --> msub.  */
      break;
    case 585:	/* smull */
      value = 584;	/* --> smaddl.  */
      break;
    case 587:	/* smnegl */
      value = 586;	/* --> smsubl.  */
      break;
    case 590:	/* umull */
      value = 589;	/* --> umaddl.  */
      break;
    case 592:	/* umnegl */
      value = 591;	/* --> umsubl.  */
      break;
    case 603:	/* ror */
      value = 602;	/* --> extr.  */
      break;
    case 703:	/* strb */
      value = 701;	/* --> sturb.  */
      break;
    case 704:	/* ldrb */
      value = 702;	/* --> ldurb.  */
      break;
    case 706:	/* ldrsb */
      value = 705;	/* --> ldursb.  */
      break;
    case 709:	/* str */
      value = 707;	/* --> stur.  */
      break;
    case 710:	/* ldr */
      value = 708;	/* --> ldur.  */
      break;
    case 713:	/* strh */
      value = 711;	/* --> sturh.  */
      break;
    case 714:	/* ldrh */
      value = 712;	/* --> ldurh.  */
      break;
    case 716:	/* ldrsh */
      value = 715;	/* --> ldursh.  */
      break;
    case 719:	/* str */
      value = 717;	/* --> stur.  */
      break;
    case 720:	/* ldr */
      value = 718;	/* --> ldur.  */
      break;
    case 722:	/* ldrsw */
      value = 721;	/* --> ldursw.  */
      break;
    case 724:	/* prfm */
      value = 723;	/* --> prfum.  */
      break;
    case 766:	/* bic */
      value = 765;	/* --> and.  */
      break;
    case 768:	/* mov */
      value = 767;	/* --> orr.  */
      break;
    case 771:	/* tst */
      value = 770;	/* --> ands.  */
      break;
    case 776:	/* uxtw */
    case 775:	/* mov */
      value = 774;	/* --> orr.  */
      break;
    case 778:	/* mvn */
      value = 777;	/* --> orn.  */
      break;
    case 782:	/* tst */
      value = 781;	/* --> ands.  */
      break;
    case 785:	/* mov */
      value = 784;	/* --> movn.  */
      break;
    case 787:	/* mov */
      value = 786;	/* --> movz.  */
      break;
    case 798:	/* sevl */
    case 797:	/* sev */
    case 796:	/* wfi */
    case 795:	/* wfe */
    case 794:	/* yield */
    case 793:	/* nop */
      value = 792;	/* --> hint.  */
      break;
    case 1062:	/* sys */
    case 1061:	/* sys */
    case 807:	/* tlbi */
    case 806:	/* ic */
    case 805:	/* dc */
    case 804:	/* at */
      value = 803;	/* --> sys.  */
      break;
    case 854:	/* staddb */
      value = 853;	/* --> ldaddb.  */
      break;
    case 857:	/* staddlb */
      value = 856;	/* --> ldaddlb.  */
      break;
    case 860:	/* staddh */
      value = 859;	/* --> ldaddh.  */
      break;
    case 863:	/* staddlh */
      value = 862;	/* --> ldaddlh.  */
      break;
    case 866:	/* stadd */
      value = 865;	/* --> ldadd.  */
      break;
    case 869:	/* staddl */
      value = 868;	/* --> ldaddl.  */
      break;
    case 872:	/* stadd */
      value = 871;	/* --> ldadd.  */
      break;
    case 875:	/* staddl */
      value = 874;	/* --> ldaddl.  */
      break;
    case 878:	/* stclrb */
      value = 877;	/* --> ldclrb.  */
      break;
    case 881:	/* stclrlb */
      value = 880;	/* --> ldclrlb.  */
      break;
    case 884:	/* stclrh */
      value = 883;	/* --> ldclrh.  */
      break;
    case 887:	/* stclrlh */
      value = 886;	/* --> ldclrlh.  */
      break;
    case 890:	/* stclr */
      value = 889;	/* --> ldclr.  */
      break;
    case 893:	/* stclrl */
      value = 892;	/* --> ldclrl.  */
      break;
    case 896:	/* stclr */
      value = 895;	/* --> ldclr.  */
      break;
    case 899:	/* stclrl */
      value = 898;	/* --> ldclrl.  */
      break;
    case 902:	/* steorb */
      value = 901;	/* --> ldeorb.  */
      break;
    case 905:	/* steorlb */
      value = 904;	/* --> ldeorlb.  */
      break;
    case 908:	/* steorh */
      value = 907;	/* --> ldeorh.  */
      break;
    case 911:	/* steorlh */
      value = 910;	/* --> ldeorlh.  */
      break;
    case 914:	/* steor */
      value = 913;	/* --> ldeor.  */
      break;
    case 917:	/* steorl */
      value = 916;	/* --> ldeorl.  */
      break;
    case 920:	/* steor */
      value = 919;	/* --> ldeor.  */
      break;
    case 923:	/* steorl */
      value = 922;	/* --> ldeorl.  */
      break;
    case 926:	/* stsetb */
      value = 925;	/* --> ldsetb.  */
      break;
    case 929:	/* stsetlb */
      value = 928;	/* --> ldsetlb.  */
      break;
    case 932:	/* stseth */
      value = 931;	/* --> ldseth.  */
      break;
    case 935:	/* stsetlh */
      value = 934;	/* --> ldsetlh.  */
      break;
    case 938:	/* stset */
      value = 937;	/* --> ldset.  */
      break;
    case 941:	/* stsetl */
      value = 940;	/* --> ldsetl.  */
      break;
    case 944:	/* stset */
      value = 943;	/* --> ldset.  */
      break;
    case 947:	/* stsetl */
      value = 946;	/* --> ldsetl.  */
      break;
    case 950:	/* stsmaxb */
      value = 949;	/* --> ldsmaxb.  */
      break;
    case 953:	/* stsmaxlb */
      value = 952;	/* --> ldsmaxlb.  */
      break;
    case 956:	/* stsmaxh */
      value = 955;	/* --> ldsmaxh.  */
      break;
    case 959:	/* stsmaxlh */
      value = 958;	/* --> ldsmaxlh.  */
      break;
    case 962:	/* stsmax */
      value = 961;	/* --> ldsmax.  */
      break;
    case 965:	/* stsmaxl */
      value = 964;	/* --> ldsmaxl.  */
      break;
    case 968:	/* stsmax */
      value = 967;	/* --> ldsmax.  */
      break;
    case 971:	/* stsmaxl */
      value = 970;	/* --> ldsmaxl.  */
      break;
    case 974:	/* stsminb */
      value = 973;	/* --> ldsminb.  */
      break;
    case 977:	/* stsminlb */
      value = 976;	/* --> ldsminlb.  */
      break;
    case 980:	/* stsminh */
      value = 979;	/* --> ldsminh.  */
      break;
    case 983:	/* stsminlh */
      value = 982;	/* --> ldsminlh.  */
      break;
    case 986:	/* stsmin */
      value = 985;	/* --> ldsmin.  */
      break;
    case 989:	/* stsminl */
      value = 988;	/* --> ldsminl.  */
      break;
    case 992:	/* stsmin */
      value = 991;	/* --> ldsmin.  */
      break;
    case 995:	/* stsminl */
      value = 994;	/* --> ldsminl.  */
      break;
    case 998:	/* stumaxb */
      value = 997;	/* --> ldumaxb.  */
      break;
    case 1001:	/* stumaxlb */
      value = 1000;	/* --> ldumaxlb.  */
      break;
    case 1004:	/* stumaxh */
      value = 1003;	/* --> ldumaxh.  */
      break;
    case 1007:	/* stumaxlh */
      value = 1006;	/* --> ldumaxlh.  */
      break;
    case 1010:	/* stumax */
      value = 1009;	/* --> ldumax.  */
      break;
    case 1013:	/* stumaxl */
      value = 1012;	/* --> ldumaxl.  */
      break;
    case 1016:	/* stumax */
      value = 1015;	/* --> ldumax.  */
      break;
    case 1019:	/* stumaxl */
      value = 1018;	/* --> ldumaxl.  */
      break;
    case 1022:	/* stuminb */
      value = 1021;	/* --> lduminb.  */
      break;
    case 1025:	/* stuminlb */
      value = 1024;	/* --> lduminlb.  */
      break;
    case 1028:	/* stuminh */
      value = 1027;	/* --> lduminh.  */
      break;
    case 1031:	/* stuminlh */
      value = 1030;	/* --> lduminlh.  */
      break;
    case 1034:	/* stumin */
      value = 1033;	/* --> ldumin.  */
      break;
    case 1037:	/* stuminl */
      value = 1036;	/* --> lduminl.  */
      break;
    case 1040:	/* stumin */
      value = 1039;	/* --> ldumin.  */
      break;
    case 1043:	/* stuminl */
      value = 1042;	/* --> lduminl.  */
      break;
    default: return NULL;
    }

  return aarch64_opcode_table + value;
}

const char*
aarch64_insert_operand (const aarch64_operand *self,
			   const aarch64_opnd_info *info,
			   aarch64_insn *code, const aarch64_inst *inst)
{
  /* Use the index as the key.  */
  int key = self - aarch64_operands;
  switch (key)
    {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 18:
    case 19:
    case 20:
    case 21:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 39:
    case 40:
      return aarch64_ins_regno (self, info, code, inst);
    case 16:
      return aarch64_ins_reg_extended (self, info, code, inst);
    case 17:
      return aarch64_ins_reg_shifted (self, info, code, inst);
    case 22:
      return aarch64_ins_ft (self, info, code, inst);
    case 32:
    case 33:
    case 34:
      return aarch64_ins_reglane (self, info, code, inst);
    case 35:
      return aarch64_ins_reglist (self, info, code, inst);
    case 36:
      return aarch64_ins_ldst_reglist (self, info, code, inst);
    case 37:
      return aarch64_ins_ldst_reglist_r (self, info, code, inst);
    case 38:
      return aarch64_ins_ldst_elemlist (self, info, code, inst);
    case 41:
    case 50:
    case 51:
    case 52:
    case 53:
    case 54:
    case 55:
    case 56:
    case 57:
    case 58:
    case 59:
    case 60:
    case 61:
    case 62:
    case 71:
    case 72:
    case 73:
    case 74:
      return aarch64_ins_imm (self, info, code, inst);
    case 42:
    case 43:
      return aarch64_ins_advsimd_imm_shift (self, info, code, inst);
    case 44:
    case 45:
    case 46:
      return aarch64_ins_advsimd_imm_modified (self, info, code, inst);
    case 63:
      return aarch64_ins_limm (self, info, code, inst);
    case 64:
      return aarch64_ins_aimm (self, info, code, inst);
    case 65:
      return aarch64_ins_imm_half (self, info, code, inst);
    case 66:
      return aarch64_ins_fbits (self, info, code, inst);
    case 68:
    case 69:
      return aarch64_ins_cond (self, info, code, inst);
    case 75:
    case 81:
      return aarch64_ins_addr_simple (self, info, code, inst);
    case 76:
      return aarch64_ins_addr_regoff (self, info, code, inst);
    case 77:
    case 78:
    case 79:
      return aarch64_ins_addr_simm (self, info, code, inst);
    case 80:
      return aarch64_ins_addr_uimm12 (self, info, code, inst);
    case 82:
      return aarch64_ins_simd_addr_post (self, info, code, inst);
    case 83:
      return aarch64_ins_sysreg (self, info, code, inst);
    case 84:
      return aarch64_ins_pstatefield (self, info, code, inst);
    case 85:
    case 86:
    case 87:
    case 88:
      return aarch64_ins_sysins_op (self, info, code, inst);
    case 89:
      return aarch64_ins_cachereg (self, info, code, inst);
    case 90:
      return aarch64_ins_cachezero (self, info, code, inst);
    case 91:
    case 92:
      return aarch64_ins_barrier (self, info, code, inst);
    case 93:
      return aarch64_ins_prfop (self, info, code, inst);
    default: assert (0); abort ();
    }
}
